cn_rail_events_dict = {
    'A': 'Arrived at location',
    'B': 'Bad order (needs repair)',
    'C': 'Came in the gate of an intermodal terminal',
    'D': 'Arrived at final destination yard or terminal',
    'E': 'Exit the gate of an intermodal terminal',
    'F': 'Flat Car has been reported in bad order (needs repair)',
    'G': 'Released from bad order (repair) and returned to service',
    'H': 'Hold status',
    'J': 'Junction delivery (interchange to another railroad)',
    'K': 'Intermodal Interchange',
    'L': 'Loaded',
    'M': 'Motor carrier move',
    'P': 'Passed a station on a train (departure)',
    'Q': 'Flat Car released from bad order (repair)',
    'R': 'Received at junction interchange from another railroad',
    'S': 'Stored',
    'U': 'Ramped, intermodal unit loaded onto a flatcar',
    'V': 'Deramped, intermodal unit removed from a flatcar',
    'W': 'Release by shipper (OK to move)',
    'X': 'Departed shipper, pickup or pull',
    'Y': 'Notification or constructive placement',
    'Z': 'Placement or delivery to consignee ',
}